export const ROBOTS_LOADING = 'ROBOTS_LOADING';
export const ROBOTS_FAILED = 'ROBOTS_FAILED';
export const ADD_ROBOTS = 'ADD_ROBOTS'; 
export const PATIENTS_LOADING = 'PATIENTS_LOADING';
export const PATIENTS_FAILED = 'PATIENTS_FAILED';
export const ADD_PATIENTS = 'ADD_PATIENTS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';
export const ADD_USERS = 'ADD_USERS';
export const ADD_INACTIVEUSERS = 'ADD_INACTIVEUSERS';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const ADD_CORRESPONDINGPATIENT = 'ADD_CORRESPONDINGPATIENT';

